version: "3.8"
services:
  dbb18:
    container_name: dbb18
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mindt
    ports:
      - 3307:3306
      
      
      
  app:
    depends_on:
      - dbb18
    restart: always
    build: .
    ports:
      - 8081:8022